=== UmbePaolo/testalpaloo/alpaloo/Scripts/App/json-schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "title": "JSON Schema for SkiDay",
  "properties": {
    "date": {
      "type": "string"
    },
    "avatar": {
      "type": "string"
    },
    "userName": {
      "type": "string"
    },
    "userSurname": {
      "type": "string"
    },
    "userId": {
      "type": "integer"
    },
    "resortName": {
      "type": "string"
    },
    "resortImgAvatar": {
      "type": "string"
    },
    "mtTotRisaliti": {
      "type": "integer"
    },
    "kmTotDiscesi": {
      "type": "integer"
    },
    "hTotAttivita": {
      "type": "integer"
    },
    "toLifts": {
      "type": "integer"
    },
    "facebookUrl": {
      "type": "string"
    },
    "liftsTaken": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "liftName": {
            "type": "string"
          },
          "liftLocation": {
            "type": "string"
          },
          "distMed": {
            "type": "integer"
          },
          "difAlt": {
            "type": "integer"
          },
          "arrAlt": {
            "type": "integer"
          },
          "startAlt": {
            "type": "integer"
          },
          "liftTime": {
            "type": "string"
          },
          "resortLogo": {
            "type": "string"
          },
          "liftResort": {
            "type": "string"
          },
          "icon": {
            "type": "string"
          }
        },
        "required": [
          "liftName",
          "liftLocation",
          "distMed",
          "difAlt",
          "arrAlt",
          "startAlt",
          "liftTime",
          "resortLogo",
          "liftResort",
          "icon"
        ]
      }
    }
  },
  "required": [
    "date",
    "avatar",
    "userName",
    "userSurname",
    "userId",
    "resortName",
    "resortImgAvatar",
    "mtTotRisaliti",
    "kmTotDiscesi",
    "hTotAttivita",
    "toLifts",
    "facebookUrl",
    "liftsTaken"
  ]
}

=== UmbePaolo/testalpaloo/alpaloo/sample.json
{
  "date": "2016-12-10T00:00:00",
  "avatar": "http://testb2c.alpaloo.com/User/Photo/6617.png",
  "userName": "Matteo",
  "userSurname": "Fossati",
  "userId": 6617,
  "resortName": "Courmayeur",
  "resortImgAvatar": "78.png",
  "mtTotRisaliti": 3100,
  "kmTotDiscesi": 0,
  "hTotAttivita": 5,
  "toLifts": 10,
  "facebookUrl": "https://www.alpaloo.com/fb-ActionDay.aspx?sid=6617|10/12/2016|Courmayeur",
  "liftsTaken": [
    {
      "liftName": "Dolonne",
      "liftLocation": "Courmayeur",
      "distMed": 0,
      "difAlt": -493,
      "arrAlt": 1212,
      "startAlt": 1705,
      "liftTime": "2016-12-10T16:29:53",
      "liftStartTop": 80,
      "liftStartLeft": 33,
      "liftEndTop": 70,
      "liftEndLeft": 39,
      "resortLogo": "78.png",
      "liftResort": "Courmayeur",
      "icon": "cabinovia.svg"
    },
    {
      "liftName": "Zerotta",
      "liftLocation": "Courmayeur",
      "distMed": 0,
      "difAlt": 558,
      "arrAlt": 2082,
      "startAlt": 1524,
      "liftTime": "2016-12-10T16:00:14",
      "liftStartTop": 54,
      "liftStartLeft": 84,
      "liftEndTop": 50,
      "liftEndLeft": 61,
      "resortLogo": "78.png",
      "liftResort": "Courmayeur",
      "icon": "seggiovia.svg"
    },
    {
      "liftName": "Dzeleuna",
      "liftLocation": "Courmayeur",
      "distMed": 0,
      "difAlt": 187,
      "arrAlt": 2075,
      "startAlt": 1888,
      "liftTime": "2016-12-10T14:07:57",
      "liftStartTop": 52,
      "liftStartLeft": 56,
      "liftEndTop": 50,
      "liftEndLeft": 61,
      "resortLogo": "78.png",
      "liftResort": "Courmayeur",
      "icon": "seggiovia.svg"
    },
    {
      "liftName": "Pra Neyron",
      "liftLocation": "Courmayeur",
      "distMed": 0,
      "difAlt": 347,
      "arrAlt": 2039,
      "startAlt": 1692,
      "liftTime": "2016-12-10T13:53:10",
      "liftStartTop": 69,
      "liftStartLeft": 35,
      "liftEndTop": 45,
      "liftEndLeft": 53,
      "resortLogo": "78.png",
      "liftResort": "Courmayeur",
      "icon": "seggiovia.svg"
    },
    {
      "liftName": "Checrouit",
      "liftLocation": "Courmayeur",
      "distMed": 0,
      "difAlt": 550,
      "arrAlt": 2260,
      "startAlt": 1710,
      "liftTime": "2016-12-10T13:13:52",
      "liftStartTop": 69,
      "liftStartLeft": 30,
      "liftEndTop": 20,
      "liftEndLeft": 48,
      "resortLogo": "78.png",
      "liftResort": "Courmayeur",
      "icon": "cabinovia.svg"
    },
    {
      "liftName": "Zerotta",
      "liftLocation": "Courmayeur",
      "distMed": 0,
      "difAlt": 558,
      "arrAlt": 2082,
      "startAlt": 1524,
      "liftTime": "2016-12-10T12:08:00",
      "liftStartTop": 54,
      "liftStartLeft": 84,
      "liftEndTop": 50,
      "liftEndLeft": 61,
      "resortLogo": "78.png",
      "liftResort": "Courmayeur",
      "icon": "seggiovia.svg"
    },
    {
      "liftName": "Peindeint",
      "liftLocation": "Courmayeur",
      "distMed": 0,
      "difAlt": 366,
      "arrAlt": 2034,
      "startAlt": 1668,
      "liftTime": "2016-12-10T11:46:04",
      "liftStartTop": 56,
      "liftStartLeft": 74,
      "liftEndTop": 58,
      "liftEndLeft": 76,
      "resortLogo": "78.png",
      "liftResort": "Courmayeur",
      "icon": "seggiovia.svg"
    },
    {
      "liftName": "Dzeleuna",
      "liftLocation": "Courmayeur",
      "distMed": 0,
      "difAlt": 187,
      "arrAlt": 2075,
      "startAlt": 1888,
      "liftTime": "2016-12-10T11:26:41",
      "liftStartTop": 52,
      "liftStartLeft": 56,
      "liftEndTop": 50,
      "liftEndLeft": 61,
      "resortLogo": "78.png",
      "liftResort": "Courmayeur",
      "icon": "seggiovia.svg"
    },
    {
      "liftName": "Pra Neyron",
      "liftLocation": "Courmayeur",
      "distMed": 0,
      "difAlt": 347,
      "arrAlt": 2039,
      "startAlt": 1692,
      "liftTime": "2016-12-10T11:13:03",
      "liftStartTop": 69,
      "liftStartLeft": 35,
      "liftEndTop": 45,
      "liftEndLeft": 53,
      "resortLogo": "78.png",
      "liftResort": "Courmayeur",
      "icon": "seggiovia.svg"
    },
    {
      "liftName": "Dolonne",
      "liftLocation": "Courmayeur",
      "distMed": 0,
      "difAlt": 493,
      "arrAlt": 1705,
      "startAlt": 1212,
      "liftTime": "2016-12-10T09:39:34",
      "liftStartTop": 70,
      "liftStartLeft": 39,
      "liftEndTop": 80,
      "liftEndLeft": 33,
      "resortLogo": "78.png",
      "liftResort": "Courmayeur",
      "icon": "cabinovia.svg"
    }
  ]
}
